Repository tektronix/tm_devices, pull requests merged in 2023-11, with the labels that each got.

#83 docs: Update basic usage with better wording for examples.
  docs/basic_usage.md
  src/tm_devices/driver_mixins/class_extension_mixin.py
Labels: documentation

#84 Update the basic usage docs and Readme
  .pre-commit-config.yaml
  CHANGELOG.md
  README.rst
  docs/basic_usage.md
  docs/glossary.md
  examples/miscellaneous/visa_connection_selectivity.py
  examples/scopes/tekscope/get_acquisition_data.py
  examples/scopes/tekscope_70k/dpojet/adding_dpojet_measurements.py
  pyproject.toml
Labels: documentation, enhancement

#85 fix: Update a few comments to have better wording.
  .github/dependabot.yml
  examples/scopes/tekscope/get_acquisition_data.py
  examples/scopes/tekscope_70k/dpojet/adding_dpojet_measurements.py
Labels: documentation

#95 ci: Update how the changelog generation macro selects PR numbers.
  python_semantic_release_templates/.macros.j2
Labels: bug, documentation

#96 Add new options for REST API devices
  CHANGELOG.md
  README.rst
  src/tm_devices/drivers/api/rest_api/rest_api_device.py
  src/tm_devices/drivers/pi/scopes/tekscope/tekscope.py
  src/tm_devices/helpers/constants_and_dataclasses.py
  tests/test_margin_testers.py
  tests/test_scopes.py
Labels: documentation, enhancement

#97 feat: Add USBTMC support for the 3706A device.
  .pre-commit-config.yaml
  CHANGELOG.md
  src/tm_devices/helpers/constants_and_dataclasses.py
Labels: enhancement

#98 Increase timeout value when installing tm_devices from pypi servers
  .github/workflows/package-release.yml
  .github/workflows/package-testpypi.yml
Labels: bug, ci/cd, gh-actions

#100 Update the Readme
  README.rst
Labels: documentation

#105 docs: Remove the TestPyPI badge from the readme.
  README.rst
Labels: documentation

#107 feat(rest_api_device): Enable sending raw data for restful api devices.
  CHANGELOG.md
  src/tm_devices/drivers/api/rest_api/rest_api_device.py
Labels: enhancement

#109 Fix import error on mac with system integrity protection
  .pre-commit-config.yaml
  CHANGELOG.md
  src/tm_devices/commands/_helpers/generic_commands.py
  src/tm_devices/components/dm_config_parser.py
  src/tm_devices/drivers/pi/pi_device.py
  src/tm_devices/drivers/pi/scopes/tekscope/tekscope.py
  src/tm_devices/helpers/functions.py
  tests/test_helpers.py
Labels: bug
