Repository tektronix/tm_devices, pull requests merged in 2023-10, with the labels that each got.

#20 Implement separate TestPyPI upload workflow
  .github/workflows/package-build.yml
  .github/workflows/package-testpypi.yml
  README.rst
Labels: enhancement, ci/cd

#21 Update python-semantic-release config settings.
  .github/workflows/package-testpypi.yml
  CONTRIBUTING.md
  pyproject.toml
Labels: bug, ci/cd

#23 Custom testpypi version creation script
  .github/workflows/package-testpypi.yml
  CONTRIBUTING.md
  pyproject.toml
  scripts/contributor_setup.py
  scripts/create_post_version_for_testpypi.py
  scripts/project_version.py
  scripts/pypi_latest_version.py
Labels: bug, ci/cd

#24 Add a wait time to allow for the package to be available to install.
  .github/workflows/package-testpypi.yml
Labels: bug, ci/cd

#25 Update test.pypi.org upload workflow
  .github/workflows/package-testpypi.yml
  src/tm_devices/drivers/pi/scopes/tekscope/tekscope.py
  tests/test_device_manager.py
Labels: enhancement, ci/cd

#26 Added a command-line script to print the available VISA resources.
  CHANGELOG.md
  README.rst
  docs/basic_usage.md
  pyproject.toml
  src/tm_devices/__init__.py
  src/tm_devices/device_manager.py
Labels: enhancement

#28 Reduce doc build time
  .gitignore
  .readthedocs.yml
  docs/conf.py
  src/tm_devices/commands/_helpers/generic_commands.py
Labels: documentation, enhancement

#29 Add workflow for official GitHub and PyPI release
  .github/workflows/package-release.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  docs/troubleshooting/contributions.md
  pyproject.toml
  python_semantic_release_templates/CHANGELOG.md.j2
  scripts/check_unreleased_changelog_items.py
Labels: enhancement, ci/cd

#30 Update git config during package release.
  .github/workflows/package-release.yml
Labels: bug, ci/cd

#31 Update changelog update process
  .github/workflows/package-release.yml
  python_semantic_release_templates/.previous_changelog_for_template.md
  python_semantic_release_templates/CHANGELOG.md.j2
Labels: bug, ci/cd

#32 Update links in Readme
  .github/workflows/package-release.yml
  README.rst
Labels: documentation, enhancement

#33 Update package release workflow with necessary permissions
  .github/workflows/package-release.yml
Labels: bug, ci/cd

#34 Update packaging workflow
  .github/workflows/package-release.yml
Labels: ci/cd

#35 ci: Update semantic release step to not use the docker container.
  .github/workflows/package-release.yml
Labels: bug, ci/cd

#36 ci: Add missing command to workflow.
  .github/workflows/package-release.yml
Labels: bug, ci/cd

#37 ci: Update workflow to enable signed commits.
  .github/workflows/package-release.yml
  .github/workflows/package-testpypi.yml
  python_semantic_release_templates/CHANGELOG.md.j2
Labels: bug, enhancement, ci/cd

#38 Update package release workflow to build correct version
  .github/workflows/codeql-analysis.yml
  .github/workflows/package-release.yml
  .github/workflows/tek-repo-lint.yml
  .github/workflows/test-code.yml
  .github/workflows/test-docs.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  python_semantic_release_templates/CHANGELOG.md.j2
Labels: bug, ci/cd

#39 Fix readme links and release workflow
  .github/workflows/package-release.yml
  CHANGELOG.md
  README.rst
  python_semantic_release_templates/CHANGELOG.md.j2
Labels: bug, documentation, ci/cd

#40 ci: Update permissions to allow the workflow to modify GitHub Releases.
  .github/workflows/package-build.yml
  .github/workflows/package-release.yml
  .github/workflows/tek-repo-lint.yml
  .github/workflows/test-code.yml
  .github/workflows/test-docs.yml
  CHANGELOG.md
  pyproject.toml
Labels: bug, ci/cd

#41 Update badge displaying total number of downloads
  .github/workflows/package-release.yml
  CHANGELOG.md
  README.rst
Labels: bug, documentation, enhancement

#66 Update the code that checks for package updates
  CHANGELOG.md
  docs/configuration.md
  pyproject.toml
  scripts/pypi_latest_version.py
  src/tm_devices/device_manager.py
  src/tm_devices/helpers/constants_and_dataclasses.py
  src/tm_devices/helpers/functions.py
  tests/conftest.py
  tests/test_helpers.py
Labels: bug, enhancement

#67 Add template for GitHub Releases
  .github/workflows/package-release.yml
  CHANGELOG.md
  docs/conf.py
  python_semantic_release_templates/.macros.j2
  python_semantic_release_templates/.previous_release_notes_for_template.md
  python_semantic_release_templates/.release_notes.md.j2
  python_semantic_release_templates/CHANGELOG.md.j2
  scripts/check_unreleased_changelog_items.py
Labels: documentation, enhancement, ci/cd

#68 ci: Update macro to enable GitHub Release template to function properly.
  CHANGELOG.md
  pyproject.toml
  python_semantic_release_templates/.macros.j2
  python_semantic_release_templates/.release_notes.md.j2
  python_semantic_release_templates/CHANGELOG.md.j2
Labels: bug, ci/cd

#69 fix: Update the version of the semantic release action used to fix a bug with the output version.
  .github/workflows/package-release.yml
  CHANGELOG.md
Labels: bug, ci/cd

#70 ci: Update workflow name and add Python 3.12 classifier
  .github/workflows/package-release.yml
  pyproject.toml
  src/tm_devices/device_manager.py
Labels: enhancement, ci/cd

#75 Update version of GitHub action used to build the package
  .github/workflows/package-build.yml
  .github/workflows/package-release.yml
  .github/workflows/package-testpypi.yml
  README.rst
  docs/conf.py
  docs/requirements.txt
  pyproject.toml
Labels: bug, ci/cd

#76 docs: Added new workflow which can deploy the documentation to GitHub Pages
  .github/workflows/deploy-documentation.yml
  README.rst
  pyproject.toml
Labels: documentation, ci/cd

#78 docs: Added instructions on how to set up commit signing with a note explaining that it is required.
  .github/workflows/deploy-documentation.yml
  CONTRIBUTING.md
Labels: documentation, enhancement

#81 fix: Handle non-standard software versions with alpha characters in the last part of the version
  CHANGELOG.md
  src/tm_devices/helpers/functions.py
  tests/test_helpers.py
Labels: bug

#80 fix: Build docs without parallelization to fix pop-up issues with sphinx-tippy
  .github/workflows/package-release.yml
  CHANGELOG.md
  pyproject.toml
Labels: bug, documentation

#82 refactor: Removed some API files that are no longer needed (outdated/broken)
  CHANGELOG.md
  README.rst
  docs/_static/favicon_readthedocs.png
  docs/conf.py
  src/tm_devices/commands/_c3g63_lpdmso/measu.py
  src/tm_devices/commands/_c69b1_lpdmso/actonevent.py
  src/tm_devices/commands/_c69b1_lpdmso/callouts.py
  src/tm_devices/commands/_c69b1_lpdmso/diag.py
  src/tm_devices/commands/_c69b1_lpdmso/ref.py
  tests/test_docs.py
Labels: bug, documentation, enhancement
