Repository tektronix/tm_devices, pull requests merged in 2024-08, with the labels that each got.

#264 Convert test-docs.yml to a reusable workflow
  .github/workflows/test-code.yml
  .github/workflows/test-docs.yml
  .readthedocs.yml
  pyproject.toml
Labels: enhancement, ci/cd

#266 docs: Update links on the Readme to point to the full GitHub URL
  README.md
  docs/macros.py
Labels: documentation

#267 feat: Custom LAN Device Name for TCPIP Connections
  .github/workflows/test-code.yml
  CHANGELOG.md
  docs/configuration.md
  pyproject.toml
  src/tm_devices/components/dm_config_parser.py
  src/tm_devices/helpers/constants_and_dataclasses.py
  tests/samples/sample_devices.toml
  tests/samples/sample_devices.yaml
  tests/test_config_parser.py
Labels: enhancement

#271 docs: Update the contribution guide to provide details on how to track the status of changes in the GitHub repo using issues
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#269 feat: Add curve query support for MSO2KB series scopes
  CHANGELOG.md
  src/tm_devices/drivers/pi/scopes/tekscope_2k/tekscope_2k.py
  src/tm_devices/helpers/constants_and_dataclasses.py
  tests/sim_devices/devices.yaml
  tests/sim_devices/scope/mso2kb.yaml
  tests/test_scopes.py
Labels: enhancement
